<?php
    /* get config from themesetting */
    $setting = Mage::helper('galavineyardsettings');
    $fonts = Mage::getModel('galavineyardsettings/config_font')->toOptionArray();
    $boxwide = Mage::getModel('galavineyardsettings/config_boxwide')->toOptionArray();
    $tmf = $setting->getMenu_TmFont();
    $h5f = $setting->getTypography_H5Font();
    if($tmf==""){
        $tmf=$h5f;
    }
    $dmf = $setting->getMenu_DmFont();
    $gf = $setting->getTypography_GeneralFont();
    if($dmf =""){
        $dmf=$gf;
    }
    $ischecked = $setting->getGeneral_WideslideFull();
    $check = $setting->getGeneral_DisableFrontendVariation();
?>
<?php if($check != 1) : ?><a href="javascript:void(0)" class="btn-toggle hide-lte0">+ open/close</a><?php endif;?>
<div id="demotool_variation" class="hide-lte0">
	<div class="variation-cp" style="display:none">
		<div class="demotool-title">Magento Theme Variations</div>
		<form method="GET" name="emvariationform" id="emvariationform" action="<?php echo $this->getSkinUrl('css/theme.css.php') ?>">
		<div class="demotool-content">
            <!-- Google Fonts -->
			<div class="demo demo-02">
				<div class="content-title"><span>Google Fonts</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
							<div class="col">
								<div class="row">
									<div class="label">Import these google fonts</div>
									<div class="input">
										<select id="em_variation_google_font" multiple="true" rows="10" size="10">
											<?php $selectedFonts = explode(',', $setting->getTypography_GoogleFonts()) ?>
											<?php foreach ($fonts as $_font): ?>
											<option value="<?php echo htmlspecialchars($_font['value']) ?>" <?php echo @in_array($_font['value'], $selectedFonts) ? 'selected="selected"' : '' ?>><?php echo $_font['label'] ?></option>
											<?php endforeach ?>
										</select>
									</div>
									<div class="desc">Select which google fonts should be imported to your site</div>
								</div>
							</div>
						</div>
					</div>
				</div>					
			</div>
			
			<!-- Element Fonts -->
			<div class="demo demo-03">
				<div class="content-title"><span>Element Fonts</span></div>
				
				<div class="wrapper-content">
					<div class="box last">
						<div class="content">
							<div class="col">
								<div class="row">
									<div class="label">General Font</div>
									<div class="input"><input type="text" name="general_font" value="<?php echo htmlspecialchars($setting->getTypography_GeneralFont()) ?>" class="input-text"/></div>
									<div class="desc">Font for body, content, text...<br/>E.g. <em>normal 12px/1.35 Arial,Helvetica,sans-serif</em></div>
								</div>
                                <input type="hidden" name="google_fonts_weights" value="<?php echo htmlspecialchars($setting->getTypography_GoogleFontWeights()) ?>" class="input-text"/>
								<div class="row">
									<div class="label">H1</div>
									<div class="input"><input type="text" name="h1_font" value="<?php echo htmlspecialchars($setting->getTypography_H1Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 22px/1.15 Arial,Helvetica,sans-serif</em></div>
								</div>
								<div class="row">
									<div class="label">H2</div>
									<div class="input"><input type="text" name="h2_font" value="<?php echo htmlspecialchars($setting->getTypography_H2Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. normal <em>normal 20px/1.25 Arial,Helvetica,sans-serif</em></div>
								</div>
								<div class="row">
									<div class="label">H3</div>
									<div class="input"><input type="text" name="h3_font" value="<?php echo htmlspecialchars($setting->getTypography_H3Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 18px/1.25 Arial,Helvetica,sans-serif</em></div>
								</div>
								<div class="row">
									<div class="label">H4</div>
									<div class="input"><input type="text" name="h4_font" value="<?php echo htmlspecialchars($setting->getTypography_H4Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 16px/1.35 Arial,Helvetica,sans-serif</em></div>
								</div>
								<div class="row">
									<div class="label">H5</div>
									<div class="input"><input type="text" name="h5_font" value="<?php echo htmlspecialchars($setting->getTypography_H5Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 14px/1.35 Arial,Helvetica,sans-serif</em></div>
								</div>
                                <div class="row">
									<div class="label">H6</div>
									<div class="input"><input type="text" name="h6_font" value="<?php echo htmlspecialchars($setting->getTypography_H6Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 12px/1.35 Arial,Helvetica,sans-serif</em></div>
								</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
            
            <!-- General -->
			<div class="demo demo-02">
				<div class="content-title"><span>Choose Your Layout Style</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
							<div class="col">
								<div class="row">
									<div class="label">Box/Wide Mode</div>
									<div class="input">
                                        <select id="em_box_wide" name="em_box_wide" class="em_box_wide select">
                                            <?php $selectedBoxWide = explode(',', $setting->getGeneral_BoxWide()) ?>
                                            <?php foreach ($boxwide as $boxwide_item): ?>
											     <option value="<?php echo htmlspecialchars($boxwide_item['value']) ?>" <?php echo @in_array($boxwide_item['value'], $selectedBoxWide) ? 'selected="selected"' : '' ?>><?php echo $boxwide_item['label'] ?></option>
											<?php endforeach ?>
                                        </select>
									</div>
									<div class="desc">Default: Box</div>
								</div>
                                <div class="row" id="emoption_wideslideshow">
                                    <div class="input">
                                        <input  id="wide_full" class="full_slideshow" type="checkbox" name="wide_full" value="wide_full" <?php if($ischecked!=0):?>checked<?php endif;?> /><span>Full Slideshow</span>
                                    </div>
                                </div>
                                <div id="page_boxconfig">
                                    <div class="row">
    									<div class="label">Page Background Color</div>
    									<div class="input"><input type="text" name="page_bg_color" value="<?php echo htmlspecialchars($setting->getGeneral_PageBgColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Default #ffffff</div>
    								</div>
                                    
                                    <div class="row">
    									<div class="label">Page Background Pattern</div>
    									<div class="input">
    										<input type="hidden" name="page_bg_image" value="<?php echo htmlspecialchars($setting->getGeneral_PageBgImage()) ?>"  />
    										<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/galavineyard/images/stripes/'; ?>
    										<?php foreach (Mage::getModel('galavineyardsettings/config_stripes')->toOptionArray() as $row):?>
    										<a href="#" class="page_bg_image" data-input-value="<?php echo htmlspecialchars($row['value']) ?>" <?php echo $setting->getGeneral_PageBgImage() == $row['value'] ? 'selected="selected"' : '' ?>>
    											<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $imgDir . $row['value'] ?>)" alt="" />
    										</a>
    										<?php endforeach ?>
    									</div>
    									<div class="desc">Specify background pattern image.</div>
    								</div>
                                    <div class="row">
    									<div class="label">Page Background Position</div>
    									<div class="input"><input type="text" name="page_bg_position" value="<?php echo htmlspecialchars($setting->getGeneral_PageBgPosition()) ?>" class="input-text"/></div>
    									<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
    								</div>
                                    <div class="row">
    									<div class="label">Page Background Repeat</div>
    									<div class="input"><input type="text" name="page_bg_repeat" value="<?php echo htmlspecialchars($setting->getGeneral_PageBgRepeat()) ?>" class="input-text"/></div>
    									<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
    								</div>
                                </div>
							</div>
						</div>
					</div>
				</div>					
			</div>
            
			<!-- Header -->
			<div class="demo demo-01">
				<div class="content-title"><span>Header</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
                                <div class="row">                              
									<div class="label">Header Background Color</div>
									<div class="input"><input type="text" name="head_bg_color" value="<?php echo htmlspecialchars($setting->getHeader_HeadBgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default #ffffff</div>
								</div>                                                
                            </div>
                            
                            <div class="col col-1">
                               
                                <div class="row">
									<div class="label">Header Text Color</div>
									<div class="input"><input type="text" name="head_text_color" value="<?php echo htmlspecialchars($setting->getHeader_HeadTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default: #000</div>
								</div>                    
                            </div>
                           
                            <div class="col">
								<div class="row">
									<div class="label">Header Background Pattern</div>
									<div class="input">
										<input type="hidden" name="head_bg_image" value="<?php echo htmlspecialchars($setting->getHeader_HeadBgImage()) ?>"  />
										<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/galavineyard/images/stripes/'; ?>
										<?php foreach (Mage::getModel('galavineyardsettings/config_stripes')->toOptionArray() as $row):?>
										<a href="#" class="head_bg_image" data-input-value="<?php echo htmlspecialchars($row['value']) ?>" <?php echo $setting->getHeader_HeadBgImage() == $row['value'] ? 'selected="selected"' : '' ?>>
											<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $imgDir . $row['value'] ?>)" alt="" />
										</a>
										<?php endforeach ?>
									</div>
									<div class="desc">Specify background pattern image.</div>
								</div>
                                <div class="row">
									<div class="label">Header Background Position</div>
									<div class="input"><input type="text" name="head_bg_position" value="<?php echo htmlspecialchars($setting->getHeader_HeadBgPosition()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
								</div>
                                <div class="row">
									<div class="label">Header Background Repeat</div>
									<div class="input"><input type="text" name="head_bg_repeat" value="<?php echo htmlspecialchars($setting->getHeader_HeadBgRepeat()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Top Menu -->
			<div class="demo demo-01">
				<div class="content-title"><span>Top Menu</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
                                <div class="row">
									<div class="label">Top Menu Background Color</div>
									<div class="input"><input type="text" name="tm_bg_color" value="<?php echo htmlspecialchars($setting->getMenu_TmBgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default #fff</div>
								</div>
                                <div class="row">
									<div class="label">Top Menu Hover/Active Text Color</div>
									<div class="input"><input type="text" name="tm_hover_text_color" value="<?php echo htmlspecialchars($setting->getMenu_TmHoverTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default: #fff</div>
								</div>                                
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">Top Menu Hover Background Color</div>
									<div class="input"><input type="text" name="tm_hover_bg_color" value="<?php echo htmlspecialchars($setting->getMenu_TmHoverBgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default #000</div>
								</div> 
                                <div class="row">
									<div class="label">Top Menu Line Color</div>
									<div class="input"><input type="text" name="tm_line_color" value="<?php echo htmlspecialchars($setting->getMenu_TmLineColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default: #cbcbcb</div>
								</div>
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">Top Menu Text Color</div>
									<div class="input"><input type="text" name="tm_text_color" value="<?php echo htmlspecialchars($setting->getMenu_TmTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default: #fff</div>
								</div>
                            </div>
                            
                            <div class="col">                                
                                <div class="row">
									<div class="label">Top Menu Font</div>
									<div class="input"><input type="text" name="tm_font" value="<?php echo htmlspecialchars($tmf) ?>" class="input-text"/></div>
									<div class="desc">Default: normal 14px/1.35 Arial,Helvetica,sans-serif</div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Dropdown Menu -->
			<div class="demo demo-01">
				<div class="content-title"><span>Dropdown Menu</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
                                <div class="row">
									<div class="label">Dropdown Menu Background Color</div>
									<div class="input"><input type="text" name="dm_bg_color" value="<?php echo htmlspecialchars($setting->getMenu_DmBgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default #fff</div>
								</div>
                                <div class="row">
									<div class="label">Dropdown Menu Text 2 Color</div>
									<div class="input"><input type="text" name="dm_text2_color" value="<?php echo htmlspecialchars($setting->getMenu_DmText2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in comment text. Default:#808080 </div>
								</div>
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">Dropdown Menu Text Color</div>
									<div class="input"><input type="text" name="dm_text_color" value="<?php echo htmlspecialchars($setting->getMenu_DmTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default:#000</div>
								</div>                                
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">Dropdown Menu Hover/Active Text Color</div>
									<div class="input"><input type="text" name="dm_hover_text_color" value="<?php echo htmlspecialchars($setting->getMenu_DmHoverTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default:#000</div>
								</div>
                            </div>
                            
                            <div class="col">                                
                                <div class="row">
									<div class="label">Dropdown Menu Font</div>
									<div class="input"><input type="text" name="dm_font" value="<?php echo htmlspecialchars($dmf) ?>" class="input-text"/></div>
									<div class="desc">Default:normal 12px/1.35 Arial,Helvetica,sans-serif</div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Body -->
			<div class="demo demo-01">
				<div class="content-title"><span>Body</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
                                <div class="row">
									<div class="label">Body Background Color</div>
									<div class="input"><input type="text" name="bd_bg_color" value="<?php echo htmlspecialchars($setting->getBody_BdBgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in body. Default #fff</div>
								</div>  
                                <div class="row">
									<div class="label">Body Text 1 Color</div>
									<div class="input"><input type="text" name="bd_text_color" value="<?php echo htmlspecialchars($setting->getBody_BdTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in normal text. Default:#000</div>
								</div>    
                                <div class="row">
									<div class="label">Body Text 4 Color</div>
									<div class="input"><input type="text" name="bd_text4_color" value="<?php echo htmlspecialchars($setting->getBody_BdText4Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in block title. Default:#fff</div>
								</div>  							
                            
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">Body Background 2 Color</div>
									<div class="input"><input type="text" name="bd_bg2_color" value="<?php echo htmlspecialchars($setting->getBody_BdBg2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in block title. Default #000</div>
								</div> 
                                <div class="row">
									<div class="label">Body Text 2 Color</div>
									<div class="input"><input type="text" name="bd_text2_color" value="<?php echo htmlspecialchars($setting->getBody_BdText2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in title of block Home Information. Default:#505050</div>
								</div>
                                <div class="row">
									<div class="label">Body Line 1 Color</div>
									<div class="input"><input type="text" name="bd_line_color" value="<?php echo htmlspecialchars($setting->getBody_BdLineColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default line color used in table boder. Default:#cbcbcb</div>
								</div>  
                              
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">Body Background 3 Color</div>
									<div class="input"><input type="text" name="bd_bg3_color" value="<?php echo htmlspecialchars($setting->getBody_BdBg3Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in tab tilte. Default: #e6e6e8</div>
								</div> 
                                <div class="row">
									<div class="label">Body Text 3 Color</div>
									<div class="input"><input type="text" name="bd_text3_color" value="<?php echo htmlspecialchars($setting->getBody_BdText3Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in "In/Out Stock", successful messages. Default:#63BF00</div>
								</div> 
                                <div class="row">
									<div class="label">Body Line 2 Color</div>
									<div class="input"><input type="text" name="bd_line2_color" value="<?php echo htmlspecialchars($setting->getBody_BdLine2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default line color used in input/ images ..  boder. Default: #dcdcdc</div>
								</div> 

                            </div>
                            
                            <div class="col">
								<div class="row">
									<div class="label">Body Background Pattern</div>
									<div class="input">
										<input type="hidden" name="bd_bg_image" value="<?php echo htmlspecialchars($setting->getBody_BdBgImage()) ?>"  />
										<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/galavineyard/images/stripes/'; ?>
										<?php foreach (Mage::getModel('galavineyardsettings/config_stripes')->toOptionArray() as $row):?>
										<a href="#" class="bd_bg_image" data-input-value="<?php echo htmlspecialchars($row['value']) ?>" <?php echo $setting->getBody_BdBgImage() == $row['value'] ? 'selected="selected"' : '' ?>>
											<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $imgDir . $row['value'] ?>)" alt="" />
										</a>
										<?php endforeach ?>
									</div>
									<div class="desc">Specify background pattern image.</div>
								</div>
                                <div class="row">
									<div class="label">Body Background Position</div>
									<div class="input"><input type="text" name="bd_bg_position" value="<?php echo htmlspecialchars($setting->getBody_BdBgPosition()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br />Default: 0 0</div>
								</div>
                                <div class="row">
									<div class="label">Body Background Repeat</div>
									<div class="input"><input type="text" name="bd_bg_repeat" value="<?php echo htmlspecialchars($setting->getBody_BdBgRepeat()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br />Default: repeat</div>
								</div>
								<div class="row">
									<div class="label">Box Shadow</div>
									<div class="input"><input type="text" name="bd_box_shadow" value="<?php echo htmlspecialchars($setting->getBody_BdBoxShadow()) ?>" class="input-text"/></div>
									<div class="desc">Default: 0 0 5px #c4c4c3</div>
								</div>
								<div class="row">
									<div class="label">Rounded Corner</div>
									<div class="input"><input type="text" name="bd_rounded_corner" value="<?php echo htmlspecialchars($setting->getBody_BdRoundedCorner()) ?>" class="input-text"/></div>
									<div class="desc">Default: 25px</div>
								</div>
                                <input type="hidden" name="additional_css_file" value="<?php echo htmlspecialchars($setting->getTypography_AdditionalCssFile()) ?>" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Footer -->
			<div class="demo demo-01">
				<div class="content-title"><span>Footer</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
                                <div class="row">
									<div class="label">Footer Background Color</div>
									<div class="input"><input type="text" name="foot_bg_color" value="<?php echo htmlspecialchars($setting->getFooter_FootBgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default: #ffffff</div>
								</div>
                                <div class="row">
									<div class="label">Footer Line 2 Color</div>
									<div class="input"><input type="text" name="foot_line2_color" value="<?php echo htmlspecialchars($setting->getFooter_FootLine2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default:#cbcbcb</div>
								</div>                                                                
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">Footer Text Color</div>
									<div class="input"><input type="text" name="foot_text_color" value="<?php echo htmlspecialchars($setting->getFooter_FootTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default: #000</div>
								</div>                             

                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">Footer Line Color</div>
									<div class="input"><input type="text" name="foot_line_color" value="<?php echo htmlspecialchars($setting->getFooter_FootLineColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default:#000</div>
								</div>
                               
                            </div>
                            <div class="col">
								<div class="row">
									<div class="label">Footer Background Pattern</div>
									<div class="input">
										<input type="hidden" name="foot_bg_image" value="<?php echo htmlspecialchars($setting->getFooter_FootBgImage()) ?>"  />
										<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/galavineyard/images/stripes/'; ?>
										<?php foreach (Mage::getModel('galavineyardsettings/config_stripes')->toOptionArray() as $row):?>
										<a href="#" class="foot_bg_image" data-input-value="<?php echo htmlspecialchars($row['value']) ?>" <?php echo $setting->getFooter_FootBgImage() == $row['value'] ? 'selected="selected"' : '' ?>>
											<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $imgDir . $row['value'] ?>)" alt="" />
										</a>
										<?php endforeach ?>
									</div>
									<div class="desc">Specify background pattern image.</div>
								</div>
                                <div class="row">
									<div class="label">Footer Background Position</div>
									<div class="input"><input type="text" name="foot_bg_position" value="<?php echo htmlspecialchars($setting->getFooter_FootBgPosition()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br />Default: 0 0</div>
								</div>
                                <div class="row">
									<div class="label">Footer Background Repeat</div>
									<div class="input"><input type="text" name="foot_bg_repeat" value="<?php echo htmlspecialchars($setting->getFooter_FootBgRepeat()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br />Default: repeat</div>
								</div>
                            </div>                            
                        </div>
                    </div>
                </div>
            </div>
			
			
			<!-- 1st Buttons -->
			<div class="demo demo-01">
				<div class="content-title"><span>1st Button</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
                                <div class="row">
									<div class="label">1st Button Background Color</div>
									<div class="input"><input type="text" name="btn1_bg_color" value="<?php echo htmlspecialchars($setting->getButton_Btn1BgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default #000000</div>
								</div>
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">1st Button Text Color</div>
									<div class="input"><input type="text" name="btn1_text_color" value="<?php echo htmlspecialchars($setting->getButton_Btn1TextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default #ffffff</div>
								</div>
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">1st Button Line Color</div>
									<div class="input"><input type="text" name="btn1_line_color" value="<?php echo htmlspecialchars($setting->getButton_Btn1LineColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default: #000000</div>
								</div>
                            </div>
                            
                            <div class="col">
								<div class="row">
									<div class="label">1st Button Font</div>
									<div class="input"><input type="text" name="btn1_font" value="<?php echo htmlspecialchars($setting->getButton_Btn1Font()) ?>" class="input-text" /></div>
									<div class="desc">Default:normal 12px/1.35 Arial, Helvetica, sans-serif</div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
			
            <!-- 2nd Buttons -->
			<div class="demo demo-01">
				<div class="content-title"><span>2nd Button</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
                                <div class="row">
									<div class="label">2nd Button Background Color</div>
									<div class="input"><input type="text" name="btn2_bg_color" value="<?php echo htmlspecialchars($setting->getButton_Btn2BgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default #f60200</div>
								</div>
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">2nd Button Text Color</div>
									<div class="input"><input type="text" name="btn2_text_color" value="<?php echo htmlspecialchars($setting->getButton_Btn2TextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default #ffffff</div>
								</div>
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">2nd Button Line Color</div>
									<div class="input"><input type="text" name="btn2_line_color" value="<?php echo htmlspecialchars($setting->getButton_Btn2LineColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default: #f60200</div>
								</div>
                            </div>
                            
                            <div class="col">
								<div class="row">
									<div class="label">2nd Button Font</div>
									<div class="input"><input type="text" name="btn2_font" value="<?php echo htmlspecialchars($setting->getButton_Btn2Font()) ?>" class="input-text" /></div>
									<div class="desc">Default: normal 12px/1.35 Arial, Helvetica, sans-serif</div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>            
			<a href="#" class="btn-reset">Reset</a>
			<a href="#" class="btn-apply">Apply Changes</a>
		</div>
		<div class="copyright">Theme designed by <a href="http://galathemes.com/" title="Premium Magento Themes &amp; Premium Magento Templates" target="_blank">Galathemes.com</a></div>
		</form>
	</div>
</div>